"""Symbolic coverage corpus.

Each problem: (domain, cells, expected). ``cells`` is a worksheet source or a
list of sources evaluated top to bottom; ``expected`` is a worksheet expression
evaluated in the same context and compared symbolically, or a dict:
  {"contains": "text"}   the plain output must contain the text
  {"ok": True}           must evaluate without error
"""

PROBLEMS = []


def p(domain, cells, expected):
    PROBLEMS.append((domain, cells if isinstance(cells, list) else [cells], expected))


# ---------------------------------------------------------------- algebra
A = "algebra"
p(A, "expand((x + 1)^3)", "x^3 + 3 x^2 + 3 x + 1")
p(A, "expand((x + y)^4)", "x^4 + 4 x^3 y + 6 x^2 y^2 + 4 x y^3 + y^4")
p(A, "factor(x^2 - 1)", "(x - 1) (x + 1)")
p(A, "factor(x^3 - 6 x^2 + 11 x - 6)", "(x - 1) (x - 2) (x - 3)")
p(A, "factor(x^4 - 1)", "(x - 1) (x + 1) (x^2 + 1)")
p(A, "simplify((x^2 - 1)/(x - 1))", "x + 1")
p(A, "simplify((x^3 + 3 x^2 + 3 x + 1)/(x + 1)^2)", "x + 1")
p(A, "cancel((x^2 + 2 x + 1)/(x + 1))", "x + 1")
p(A, "apart(1/(x^2 - 1), x)", "1/(2 (x - 1)) - 1/(2 (x + 1))")
p(A, "apart((3 x + 5)/(x^2 + 3 x + 2), x)", "2/(x + 1) + 1/(x + 2)")
p(A, "together(1/x + 1/y)", "(x + y)/(x y)")
p(A, "collect(3 x^2 + x y + 2 x^2, x)", "5 x^2 + x y")
p(A, "radsimp(1/(1 + sqrt(2)))", "sqrt(2) - 1")
p(A, "sqrtdenest(sqrt(5 + 2 sqrt(6)))", "sqrt(2) + sqrt(3)")
p(A, "powsimp(x^a x^b)", "x^(a + b)")
p(A, "subs(x^2 + 1, x, 3)", "10")
p(A, "subs(x^2 + y, [[x, 2], [y, 3]])", "7")
p(A, "nsimplify(0.5)", "1/2")
p(A, "nsimplify(0.333333333333333)", "1/3")
p(A, "ratsimp(1/x + (x + 1)/x)", "(x + 2)/x")
p(A, "rewrite(cos(x), exp)", "exp(i x)/2 + exp(-i x)/2")
p(A, "gammasimp(gamma(x + 1)/gamma(x))", "x")
p(A, "separatevars(x y + x)", "x (y + 1)")
p(A, "numer((x + 1)/(x - 1))", "x + 1")
p(A, "denom((x + 1)/(x - 1))", "x - 1")
p(A, "gcd(12, 18)", "6")
p(A, "lcm(4, 6)", "12")
p(A, "gcd(x^2 - 1, x^2 - 2 x + 1)", "x - 1")
p(A, "(2 + 3 i) (4 - i)", "11 + 10 i")
p(A, "sqrt(-4)", "2 i")
p(A, "exp(i pi)", "-1")
p(A, "abs(3 + 4 i)", "5")
p(A, "arg(i)", "pi/2")
p(A, "conj(1 + 2 i)", "1 - 2 i")
p(A, "re((1 + 2 i)^2)", "-3")
p(A, "expand((1 + i)^4)", "-4")
p(A, ["assume x real", "expand_complex(exp(i x))"], "i sin(x) + cos(x)")
p(A, "polar(1 + i)", "[sqrt(2), pi/4]")
p(A, "residue(1/(z^2 + 1), z, i)", "-i/2")
p(A, "5!", "120")
p(A, "binomial(5, 2)", "10")
p(A, "sqrt(8)", "2 sqrt(2)")
p(A, "(1/3 + 1/6)", "1/2")
p(A, "2^10", "1024")
p(A, "cbrt(27)", "3")
p(A, "root(32, 5)", "2")
p(A, "log(100, 10)", "2")
p(A, "ln(e^3)", "3")
p(A, "log2(1024)", "10")

# ---------------------------------------------------------------- assumptions
S = "assumptions"
p(S, ["assume x > 0", "sqrt(x^2)"], "x")
p(S, ["assume x real", "simplify(abs(x)^2)"], "x^2")
p(S, ["assume n integer", "simplify((-1)^(2 n))"], "1")
p(S, ["assume n integer", "simplify(sin(n pi))"], "0")
p(S, ["assume x > 0, y > 0", "logcombine(ln(x) + ln(y))"], "ln(x y)")
p(S, ["assume x > 0, y > 0", "expand_log(ln(x y))"], "ln(x) + ln(y)")
p(S, ["assume x > 0", "expand_log(ln(x^3))"], "3 ln(x)")
p(S, ["assume a > 0", "integrate(exp(-a x), x, 0, oo)"], "1/a")
p(S, ["assume n positive integer", "integrate(x^n, x, 0, 1)"], "1/(n + 1)")
p(S, ["assume x real", "solve(x^2 == -1, x)"], "[]")
p(S, ["assume x, y real", "simplify(abs(x y))"], "abs(x) abs(y)")
p(S, ["assume k even", "simplify(cos(k pi))"], "1")

# ---------------------------------------------------------------- trigonometry
T = "trigonometry"
p(T, "sin(pi/3)", "sqrt(3)/2")
p(T, "cos(pi/4)", "sqrt(2)/2")
p(T, "tan(pi/4)", "1")
p(T, "sin(30 deg)", "1/2")
p(T, "asin(1)", "pi/2")
p(T, "acos(1/2)", "pi/3")
p(T, "atan2(1, 1)", "pi/4")
p(T, "simplify(sin(x)^2 + cos(x)^2)", "1")
p(T, "trigsimp(sin(2 x)/(2 sin(x)))", "cos(x)")
p(T, "expand_trig(sin(2 x))", "2 sin(x) cos(x)")
p(T, "expand_trig(cos(2 x))", "2 cos(x)^2 - 1")
p(T, "expand_trig(tan(x + y))", "(tan(x) + tan(y))/(1 - tan(x) tan(y))")
p(T, "simplify(cosh(x)^2 - sinh(x)^2)", "1")
p(T, "trigsimp(1 + tan(x)^2)", "1/cos(x)^2")
p(T, "simplify(sin(x + pi/2))", "cos(x)")
p(T, "rewrite(sinh(x), exp)", "exp(x)/2 - exp(-x)/2")

# ---------------------------------------------------------------- equations
E = "equations"
p(E, "solve(x^2 - 5 x + 6 == 0, x)", "[2, 3]")
p(E, "solve(a x^2 + b x + c == 0, x)", "[(-b - sqrt(b^2 - 4 a c))/(2 a), (-b + sqrt(b^2 - 4 a c))/(2 a)]")
p(E, "solve(x^3 - 6 x^2 + 11 x - 6 == 0, x)", "[1, 2, 3]")
p(E, "solve(x^2 + 1 == 0, x)", "[-i, i]")
p(E, "solve(exp(x) == 5, x)", "[ln(5)]")
p(E, "solve(2^x == 8, x)", "[3]")
p(E, "solve(ln(x) == 2, x)", "[e^2]")
p(E, "solve(sin(x) == 1/2, x)", "[pi/6, 5 pi/6]")
p(E, "solve(abs(x - 1) == 2, x)", "[-1, 3]")
p(E, "solve(sqrt(x + 3) == x - 3, x)", "[6]")
p(E, "solve(x^4 - 5 x^2 + 4 == 0, x)", "[-2, -1, 1, 2]")
p(E, "solve([x + y == 3, x - y == 1], [x, y])", "[x == 2, y == 1]")
p(E, "solve([2 x + 3 y == 7, x - y == 1], [x, y])", "[x == 2, y == 1]")
p(E, "solve([x^2 + y^2 == 25, x + y == 7], [x, y])", "[[x == 3, y == 4], [x == 4, y == 3]]")
p(E, "solve([x + y + z == 6, x - y == 1, y + z == 4], [x, y, z])", "[x == 2, y == 1, z == 3]")
p(E, "linsolve([x + y == 3, x - y == 1], x, y)", "[[x == 2, y == 1]]")
p(E, "solve_real(x^4 == 1, x)", "[-1, 1]")
p(E, "solve_real(x^2 == -1, x)", "[]")
p(E, "solve_ineq(x^2 - 4 < 0, x)", {"contains": "(-2 < x) & (x < 2)"})
p(E, "solve_ineq(2 x + 1 >= 5, x)", {"contains": "(2 <= x)"})
p(E, "solve_ineq(abs(x) < 3, x)", {"contains": "(-3 < x) & (x < 3)"})
p(E, "solve(x exp(x) == 1, x)", "[lambertw(1)]")
p(E, "solve(x^2 == 4 m^2, x)", "[-2 m, 2 m]")
p(E, "solve(cos(x) == x, x)", {"error": "nsolve"})
p(E, "nsolve(cos(x) == x, x, 1)", {"contains": "0.7390851"})
p(E, "nsolve([x^2 + y^2 == 1, x == y], [x, y], [1, 1])", {"contains": "0.707106"})
p(E, "roots(x^3 - 3 x^2 + 3 x - 1, x)", "[1, 1, 1]")
p(E, "solve(y == m x + b, x)", "[(y - b)/m]")
p(E, ["f(x) = x^2 - 2", "solve(f(x) == 0, x)"], "[-sqrt(2), sqrt(2)]")
p(E, "solve(1/x + 1/(x + 1) == 1, x)", "[1/2 - sqrt(5)/2, 1/2 + sqrt(5)/2]")
p(E, "solve(x^2 - 2 x + 1 == 0, x)", "[1]")

# ---------------------------------------------------------------- polynomials
P = "polynomials"
p(P, "degree(x^3 + x, x)", "3")
p(P, "coeff(3 x^2 + 2 x + 1, x, 2)", "3")
p(P, "coeffs(3 x^2 + 2 x + 1, x)", "[3, 2, 1]")
p(P, "discriminant(a x^2 + b x + c, x)", "b^2 - 4 a c")
p(P, "resultant(x^2 - 1, x - 1, x)", "0")
p(P, "quo(x^3 - 1, x - 1, x)", "x^2 + x + 1")
p(P, "rem(x^3, x - 2, x)", "8")
p(P, "interpolate([[1, 1], [2, 4], [3, 9]], x)", "x^2")
p(P, "horner(x^3 + 2 x^2 + 3 x + 4, x)", "x (x (x + 2) + 3) + 4")
p(P, "groebner([x^2 + y^2 - 1, x - y], x, y)", {"ok": True})
p(P, "factor(x^2 + 2 x y + y^2)", "(x + y)^2")
p(P, "expand((x - 1) (x + 1) (x^2 + 1))", "x^4 - 1")

# ---------------------------------------------------------------- calculus: derivatives
D = "derivatives"
p(D, "diff(x^3, x)", "3 x^2")
p(D, "diff(sin(x) x^2, x)", "x^2 cos(x) + 2 x sin(x)")
p(D, "diff(x^3, x, 2)", "6 x")
p(D, "diff(x^2 y^3, x, y)", "6 x y^2")
p(D, "diff(exp(x^2), x)", "2 x exp(x^2)")
p(D, "diff(ln(x), x)", "1/x")
p(D, "diff(tan(x), x)", "1 + tan(x)^2")
p(D, "diff(x^x, x)", "x^x (ln(x) + 1)")
p(D, "diff(asin(x), x)", "1/sqrt(1 - x^2)")
p(D, "diff(sqrt(1 + x^2), x)", "x/sqrt(1 + x^2)")
p(D, ["f(x) = x^3", "f'(2)"], "12")
p(D, ["f(x) = x^3", "f''(x)"], "6 x")
p(D, ["f(x) = sin(x)", "f'(x)"], "cos(x)")
p(D, ["g(t) = t^2 e^t", "g'(t)"], "t^2 e^t + 2 t e^t")
p(D, "doit(derivative(x^4, x))", "4 x^3")
p(D, "diff(abs(x), x)", {"ok": True})
p(D, "gradient(x^2 + y^2, [x, y])", "matrix([2 x, 2 y])")
p(D, "divergence([x^2, y^2], [x, y])", "2 x + 2 y")
p(D, "curl([-y, x, 0], [x, y, z])", "matrix([0, 0, 2])")
p(D, "laplacian(x^2 + y^2, [x, y])", "4")
p(D, "hessian(x^2 y, [x, y])", "matrix([[2 y, 2 x], [2 x, 0]])")
p(D, "jacobian([x y, x + y], [x, y])", "matrix([[y, x], [1, 1]])")

# ---------------------------------------------------------------- calculus: integrals
I = "integrals"
p(I, "integrate(x^2, x)", "x^3/3")
p(I, "integrate(x^2, x, 0, 1)", "1/3")
p(I, "integrate(1/x, x, 1, e)", "1")
p(I, "integrate(exp(-x^2), x, -oo, oo)", "sqrt(pi)")
p(I, "integrate(1/(1 + x^2), x, -oo, oo)", "pi")
p(I, "integrate(sin(x)^2, x)", "x/2 - sin(2 x)/4")
p(I, "integrate(x exp(x), x)", "(x - 1) exp(x)")
p(I, "integrate(ln(x), x)", "x ln(x) - x")
p(I, "integrate(sqrt(1 - x^2), x, -1, 1)", "pi/2")
p(I, "integrate(1/(x^2 - 1), x)", "ln(x - 1)/2 - ln(x + 1)/2")
p(I, "integrate(x y, x, 0, 1, y, 0, 2)", "1")
p(I, "integrate(x y, x, y)", "x^2 y^2/4")
p(I, "integrate(exp(-x) sin(x), x, 0, oo)", "1/2")
p(I, "integrate(x^2 exp(-x), x, 0, oo)", "2")
p(I, "integrate(1/sqrt(x), x, 0, 1)", "2")
p(I, "integrate(sec(x)^2, x)", "tan(x)")
p(I, "integrate(1/(x ln(x)), x)", "ln(ln(x))")
p(I, "integrate(cos(x)^3, x)", "sin(x) - sin(x)^3/3")
p(I, "integrate(x/(x^2 + 1), x)", "ln(x^2 + 1)/2")
p(I, "integrate(sin(x)/x, x, 0, oo)", "pi/2")
p(I, "integrate(heaviside(x - 1), x, 0, 2)", "1")
p(I, "integrate(dirac(x), x, -1, 1)", "1")
p(I, "doit(integral(x^2, x, 0, 1))", "1/3")
p(I, "integral(x^2, x, 0, 1)", {"contains": "Integral"})
p(I, "nintegrate(exp(-x^2), x, 0, 2)", {"contains": "0.88208139"})
p(I, "nintegrate(sin(x)/x, x, 0, 10)", {"contains": "1.6583475"})
p(I, "integrate(2 m x, x, 0, 3 s)", "9 m s^2")

# ---------------------------------------------------------------- limits & series
L = "limits and series"
p(L, "limit(sin(x)/x, x, 0)", "1")
p(L, "limit((1 + 1/n)^n, n, oo)", "e")
p(L, "limit(1/x, x, 0, 1)", "oo")
p(L, "limit(1/x, x, 0, -1)", "-oo")
p(L, "limit((x^2 - 1)/(x - 1), x, 1)", "2")
p(L, "limit(x ln(x), x, 0, 1)", "0")
p(L, "limit((1 - cos(x))/x^2, x, 0)", "1/2")
p(L, "limit(exp(-x) x^3, x, oo)", "0")
p(L, "limit((sqrt(x + 1) - 1)/x, x, 0)", "1/2")
p(L, "series(exp(x), x, 0, 4)", "1 + x + x^2/2 + x^3/6")
p(L, "series(sin(x), x, 0, 6)", "x - x^3/6 + x^5/120")
p(L, "series(ln(x), x, 1, 3)", "(x - 1) - (x - 1)^2/2")
p(L, "series(1/(1 - x), x, 0, 4)", "1 + x + x^2 + x^3")
p(L, "series(cos(x), x, 0, 6)", "1 - x^2/2 + x^4/24")
p(L, "series(atan(x), x, 0, 6)", "x - x^3/3 + x^5/5")
p(L, "sum(k, k, 1, n)", "n (n + 1)/2")
p(L, "sum(k^2, k, 1, n)", "n (n + 1) (2 n + 1)/6")
p(L, "sum(1/k^2, k, 1, oo)", "pi^2/6")
p(L, "sum(1/2^k, k, 0, oo)", "2")
p(L, "sum(binomial(n, k), k, 0, n)", "2^n")
p(L, "sum(1/(k (k + 1)), k, 1, oo)", "1")
p(L, "sum(x^k/k!, k, 0, oo)", "exp(x)")
p(L, "product(k, k, 1, n)", "n!")
p(L, "product(2, k, 1, n)", "2^n")
p(L, "fourier_series(x, x, 3)", "2 sin(x) - sin(2 x) + 2 sin(3 x)/3")

# ---------------------------------------------------------------- ODEs & recurrences
O = "differential equations"
p(O, "dsolve(D(y, x) == y, y, x)", {"contains": "C1*exp(x)"})
p(O, "dsolve(D(y, x, 2) + 4 y == 0, y, x)", {"contains": "sin(2*x)"})
p(O, "dsolve(D(y, x) == -2 y, y, x, 0, 3)", "3 exp(-2 x)")
p(O, "dsolve(D(y, x, 2) - y == x, y, x)", {"contains": "exp(x)"})
p(O, "dsolve(D(y, x) == x y, y, x, 0, 1)", "exp(x^2/2)")
p(O, "dsolve(D(y, x, 2) + y == 0, y, x, 0, 0, 1)", "sin(x)")
p(O, "dsolve(D(y, t) + 2 y == exp(-t), y, t, 0, 0)", "exp(-t) - exp(-2 t)")
p(O, "dsolve(D(y, x) == y^2, y, x, 0, 1)", "-1/(x - 1)")
p(O, ["sol = odesolve(-y, y, x, 0, 1, 5)", "sol(1)"], {"contains": "0.3678"})
p(O, ["sol = odesolve(-y, y, x, 0, 1, 5)", "sol(x)"], {"contains": "y_sol(x)"})
p("transforms", "laplace(f, t, s)", "f/s")
p(A, "solve(a x^2 + b x + c == 0, c)", "[-a x^2 - b x]")
p(S, ["assume x > 0, y != 0", "sqrt(x^2) y/y"], "x")
p(A, "s + t + m + g", "g + m + s + t")
p(O, "rsolve(a[n+1] == 2 a[n], a, n, 1)", "2^n")
p(O, "rsolve(a[n+2] == a[n+1] + a[n], a, n, 0, 1)", {"contains": "sqrt(5)"})
p(O, "rsolve(a[n+1] == a[n] + n, a, n, 0)", "n (n - 1)/2")

# ---------------------------------------------------------------- transforms
X = "transforms"
p(X, ["assume a > 0", "laplace(exp(-a t), t, s)"], "1/(s + a)")
p(X, "laplace(t^2, t, s)", "2/s^3")
p(X, "laplace(sin(t), t, s)", "1/(s^2 + 1)")
p(X, "laplace(heaviside(t - 1), t, s)", "exp(-s)/s")
p(X, "ilaplace(1/(s + a), s, t)", "exp(-a t) heaviside(t)")
p(X, "ilaplace(1/s^2, s, t)", "t heaviside(t)")
p(X, "ilaplace(s/(s^2 + 4), s, t)", "cos(2 t) heaviside(t)")
p(X, "fourier(exp(-x^2), x, k)", "sqrt(pi) exp(-pi^2 k^2)")
p(X, "ifourier(sqrt(pi) exp(-pi^2 k^2), k, x)", "exp(-x^2)")
p(X, "ztransform(1, n, z)", {"ok": True})

# ---------------------------------------------------------------- linear algebra
M = "linear algebra"
p(M, "det(matrix([[1, 2], [3, 4]]))", "-2")
p(M, "inv(matrix([[1, 2], [3, 4]]))", "matrix([[-2, 1], [3/2, -1/2]])")
p(M, "transpose(matrix([[1, 2], [3, 4]]))", "matrix([[1, 3], [2, 4]])")
p(M, "matrix([[1, 2], [3, 4]]) matrix([[1], [1]])", "matrix([[3], [7]])")
p(M, "matrix([[1, 2], [3, 4]])^2", "matrix([[7, 10], [15, 22]])")
p(M, "eigenvals(matrix([[2, 0], [0, 3]]))", "[2, 3]")
p(M, "eigenvals(matrix([[2, 1], [1, 2]]))", "[1, 3]")
p(M, "rank(matrix([[1, 2], [2, 4]]))", "1")
p(M, "nullspace(matrix([[1, 2], [2, 4]]))", "[matrix([-2, 1])]")
p(M, "trace(matrix([[1, 2], [3, 4]]))", "5")
p(M, "charpoly(matrix([[2, 1], [1, 2]]), lam)", "lam^2 - 4 lam + 3")
p(M, "rref(matrix([[1, 2, 3], [4, 5, 6]]))", "matrix([[1, 0, -1], [0, 1, 2]])")
p(M, "solve_linear(matrix([[2, 1], [1, 3]]), [3, 5])", "matrix([4/5, 7/5])")
p(M, "expm(matrix([[0, 1], [-1, 0]]) t)", "matrix([[cos(t), sin(t)], [-sin(t), cos(t)]])")
p(M, "dot([1, 2, 3], [4, 5, 6])", "32")
p(M, "cross([1, 0, 0], [0, 1, 0])", "matrix([0, 0, 1])")
p(M, "norm([3, 4])", "5")
p(M, "det(matrix([[a, b], [c, d]]))", "a d - b c")
p(M, "inv(matrix([[a, b], [c, d]]))", "matrix([[d, -b], [-c, a]])/(a d - b c)")
p(M, "det(identity(3))", "1")
p(M, "diagonalize(matrix([[2, 0], [0, 3]]))", {"ok": True})
p(M, "eigenvects(matrix([[2, 0], [0, 3]]))", {"ok": True})
p(M, "lu(matrix([[4, 3], [6, 3]]))", {"ok": True})
p(M, "qr(matrix([[1, 0], [0, 1]]))", {"ok": True})
p(M, "det(matrix([[1, 2, 3], [4, 5, 6], [7, 8, 10]]))", "-3")

# ---------------------------------------------------------------- number theory & combinatorics
N = "number theory"
p(N, "isprime(97)", {"contains": "True"})
p(N, "isprime(91)", {"contains": "False"})
p(N, "prime(10)", "29")
p(N, "nextprime(100)", "101")
p(N, "primefactors(360)", "[2, 3, 5]")
p(N, "factorint(360)", "[[2, 3], [3, 2], [5, 1]]")
p(N, "divisors(12)", "[1, 2, 3, 4, 6, 12]")
p(N, "totient(36)", "12")
p(N, "invmod(3, 7)", "5")
p(N, "powmod(2, 100, 7)", "2")
p(N, "mod(17, 5)", "2")
p(N, "fibonacci(10)", "55")
p(N, "bernoulli(4)", "-1/30")
p(N, "catalan(5)", "42")
p(N, "bell(4)", "15")
p(N, "stirling(4, 2)", "7")
p(N, "partitions(5)", "7")
p(N, "factorial2(7)", "105")
p(N, "rising(x, 3)", "x (x + 1) (x + 2)")
p(N, "multinomial(2, 1, 1)", "12")
p(N, "isqrt(50)", "7")

# ---------------------------------------------------------------- special functions
F = "special functions"
p(F, "gamma(1/2)", "sqrt(pi)")
p(F, "gamma(5)", "24")
p(F, "beta(2, 3)", "1/12")
p(F, "erf(oo)", "1")
p(F, "zeta(2)", "pi^2/6")
p(F, "zeta(4)", "pi^4/90")
p(F, "besselj(0, 0)", "1")
p(F, "legendre(2, x)", "(3 x^2 - 1)/2")
p(F, "hermite(2, x)", "4 x^2 - 2")
p(F, "chebyshevt(3, x)", "4 x^3 - 3 x")
p(F, "laguerre(2, x)", "x^2/2 - 2 x + 1")
p(F, "diff(erf(x), x)", "2 exp(-x^2)/sqrt(pi)")
p(F, "lambertw(0)", "0")
p(F, "digamma(1)", "-EulerGamma")
p(F, "integrate(exp(-x^2), x)", "sqrt(pi) erf(x)/2")
p(F, "elliptic_k(0)", "pi/2")

# ---------------------------------------------------------------- units (already tested; kept for coverage)
U = "units"
p(U, ["m = 2 kg", "a = 3 m/s^2", "F = m a -> N"], "6 N")
p(U, "5 km -> m", "5000 m")
p(U, "100 kmh -> m/s", "250 m/s / 9")
p(U, "2/s^3 + 1/s", "2/s^3 + 1/s")
p(U, "x = 3 m\nx -> cm", "300 cm")
p(U, "asin(1/2) -> deg", "30 deg")
p(U, "2 km + 3 m", "2003 m")
p(U, "1 kWh -> J", "3600000 J")
