"""Symbolic coverage corpus.

Each problem: (domain, cells, expected). ``cells`` is a worksheet source or a
list of sources evaluated top to bottom; ``expected`` is a worksheet expression
evaluated in the same context and compared symbolically, or a dict:
  {"contains": "text"}   the plain output must contain the text
  {"ok": True}           must evaluate without error
"""

PROBLEMS = []


def p(domain, cells, expected):
    PROBLEMS.append((domain, cells if isinstance(cells, list) else [cells], expected))


# ---------------------------------------------------------------- algebra
A = "algebra"
p(A, "expand((x + 1)^3)", "x^3 + 3 x^2 + 3 x + 1")
p(A, "expand((x + y)^4)", "x^4 + 4 x^3 y + 6 x^2 y^2 + 4 x y^3 + y^4")
p(A, "factor(x^2 - 1)", "(x - 1) (x + 1)")
p(A, "factor(x^3 - 6 x^2 + 11 x - 6)", "(x - 1) (x - 2) (x - 3)")
p(A, "factor(x^4 - 1)", "(x - 1) (x + 1) (x^2 + 1)")
p(A, "simplify((x^2 - 1)/(x - 1))", "x + 1")
p(A, "simplify((x^3 + 3 x^2 + 3 x + 1)/(x + 1)^2)", "x + 1")
p(A, "cancel((x^2 + 2 x + 1)/(x + 1))", "x + 1")
p(A, "apart(1/(x^2 - 1), x)", "1/(2 (x - 1)) - 1/(2 (x + 1))")
p(A, "apart((3 x + 5)/(x^2 + 3 x + 2), x)", "2/(x + 1) + 1/(x + 2)")
p(A, "together(1/x + 1/y)", "(x + y)/(x y)")
p(A, "collect(3 x^2 + x y + 2 x^2, x)", "5 x^2 + x y")
p(A, "radsimp(1/(1 + sqrt(2)))", "sqrt(2) - 1")
p(A, "sqrtdenest(sqrt(5 + 2 sqrt(6)))", "sqrt(2) + sqrt(3)")
p(A, "powsimp(x^a x^b)", "x^(a + b)")
p(A, "subs(x^2 + 1, x, 3)", "10")
p(A, "subs(x^2 + y, [[x, 2], [y, 3]])", "7")
p(A, "nsimplify(0.5)", "1/2")
p(A, "nsimplify(0.333333333333333)", "1/3")
p(A, "ratsimp(1/x + (x + 1)/x)", "(x + 2)/x")
p(A, "rewrite(cos(x), exp)", "exp(i x)/2 + exp(-i x)/2")
p(A, "gammasimp(gamma(x + 1)/gamma(x))", "x")
p(A, "separatevars(x y + x)", "x (y + 1)")
p(A, "numer((x + 1)/(x - 1))", "x + 1")
p(A, "denom((x + 1)/(x - 1))", "x - 1")
p(A, "gcd(12, 18)", "6")
p(A, "lcm(4, 6)", "12")
p(A, "gcd(x^2 - 1, x^2 - 2 x + 1)", "x - 1")
p(A, "(2 + 3 i) (4 - i)", "11 + 10 i")
p(A, "sqrt(-4)", "2 i")
p(A, "exp(i pi)", "-1")
p(A, "abs(3 + 4 i)", "5")
p(A, "arg(i)", "pi/2")
p(A, "conj(1 + 2 i)", "1 - 2 i")
p(A, "re((1 + 2 i)^2)", "-3")
p(A, "expand((1 + i)^4)", "-4")
p(A, ["assume x real", "expand_complex(exp(i x))"], "i sin(x) + cos(x)")
p(A, "polar(1 + i)", "[sqrt(2), pi/4]")
p(A, "residue(1/(z^2 + 1), z, i)", "-i/2")
p(A, "5!", "120")
p(A, "binomial(5, 2)", "10")
p(A, "sqrt(8)", "2 sqrt(2)")
p(A, "(1/3 + 1/6)", "1/2")
p(A, "2^10", "1024")
p(A, "cbrt(27)", "3")
p(A, "root(32, 5)", "2")
p(A, "log(100, 10)", "2")
p(A, "ln(e^3)", "3")
p(A, "log2(1024)", "10")

# ---------------------------------------------------------------- assumptions
S = "assumptions"
p(S, ["assume x > 0", "sqrt(x^2)"], "x")
p(S, ["assume x real", "simplify(abs(x)^2)"], "x^2")
p(S, ["assume n integer", "simplify((-1)^(2 n))"], "1")
p(S, ["assume n integer", "simplify(sin(n pi))"], "0")
p(S, ["assume x > 0, y > 0", "logcombine(ln(x) + ln(y))"], "ln(x y)")
p(S, ["assume x > 0, y > 0", "expand_log(ln(x y))"], "ln(x) + ln(y)")
p(S, ["assume x > 0", "expand_log(ln(x^3))"], "3 ln(x)")
p(S, ["assume a > 0", "integrate(exp(-a x), x, 0, oo)"], "1/a")
p(S, ["assume n positive integer", "integrate(x^n, x, 0, 1)"], "1/(n + 1)")
p(S, ["assume x real", "solve(x^2 == -1, x)"], "[]")
p(S, ["assume x, y real", "simplify(abs(x y))"], "abs(x) abs(y)")
p(S, ["assume k even", "simplify(cos(k pi))"], "1")

# ---------------------------------------------------------------- trigonometry
T = "trigonometry"
p(T, "sin(pi/3)", "sqrt(3)/2")
p(T, "cos(pi/4)", "sqrt(2)/2")
p(T, "tan(pi/4)", "1")
p(T, "sin(30 deg)", "1/2")
p(T, "asin(1)", "pi/2")
p(T, "acos(1/2)", "pi/3")
p(T, "atan2(1, 1)", "pi/4")
p(T, "simplify(sin(x)^2 + cos(x)^2)", "1")
p(T, "trigsimp(sin(2 x)/(2 sin(x)))", "cos(x)")
p(T, "expand_trig(sin(2 x))", "2 sin(x) cos(x)")
p(T, "expand_trig(cos(2 x))", "2 cos(x)^2 - 1")
p(T, "expand_trig(tan(x + y))", "(tan(x) + tan(y))/(1 - tan(x) tan(y))")
p(T, "simplify(cosh(x)^2 - sinh(x)^2)", "1")
p(T, "trigsimp(1 + tan(x)^2)", "1/cos(x)^2")
p(T, "simplify(sin(x + pi/2))", "cos(x)")
p(T, "rewrite(sinh(x), exp)", "exp(x)/2 - exp(-x)/2")

# ---------------------------------------------------------------- equations
E = "equations"
p(E, "solve(x^2 - 5 x + 6 == 0, x)", "[2, 3]")
p(E, "solve(a x^2 + b x + c == 0, x)", "[(-b - sqrt(b^2 - 4 a c))/(2 a), (-b + sqrt(b^2 - 4 a c))/(2 a)]")
p(E, "solve(x^3 - 6 x^2 + 11 x - 6 == 0, x)", "[1, 2, 3]")
p(E, "solve(x^2 + 1 == 0, x)", "[-i, i]")
p(E, "solve(exp(x) == 5, x)", "[ln(5)]")
p(E, "solve(2^x == 8, x)", "[3]")
p(E, "solve(ln(x) == 2, x)", "[e^2]")
p(E, "solve(sin(x) == 1/2, x)", "[pi/6, 5 pi/6]")
p(E, "solve(abs(x - 1) == 2, x)", "[-1, 3]")
p(E, "solve(sqrt(x + 3) == x - 3, x)", "[6]")
p(E, "solve(x^4 - 5 x^2 + 4 == 0, x)", "[-2, -1, 1, 2]")
p(E, "solve([x + y == 3, x - y == 1], [x, y])", "[x == 2, y == 1]")
p(E, "solve([2 x + 3 y == 7, x - y == 1], [x, y])", "[x == 2, y == 1]")
p(E, "solve([x^2 + y^2 == 25, x + y == 7], [x, y])", "[[x == 3, y == 4], [x == 4, y == 3]]")
p(E, "solve([x + y + z == 6, x - y == 1, y + z == 4], [x, y, z])", "[x == 2, y == 1, z == 3]")
p(E, "linsolve([x + y == 3, x - y == 1], x, y)", "[[x == 2, y == 1]]")
p(E, "solve_real(x^4 == 1, x)", "[-1, 1]")
p(E, "solve_real(x^2 == -1, x)", "[]")
p(E, "solve_ineq(x^2 - 4 < 0, x)", {"contains": "(-2 < x) & (x < 2)"})
p(E, "solve_ineq(2 x + 1 >= 5, x)", {"contains": "(2 <= x)"})
p(E, "solve_ineq(abs(x) < 3, x)", {"contains": "(-3 < x) & (x < 3)"})
p(E, "solve(x exp(x) == 1, x)", "[lambertw(1)]")
p(E, "solve(x^2 == 4 m^2, x)", "[-2 m, 2 m]")
p(E, "solve(cos(x) == x, x)", {"error": "nsolve"})
p(E, "nsolve(cos(x) == x, x, 1)", {"contains": "0.7390851"})
p(E, "nsolve([x^2 + y^2 == 1, x == y], [x, y], [1, 1])", {"contains": "0.707106"})
p(E, "roots(x^3 - 3 x^2 + 3 x - 1, x)", "[1, 1, 1]")
p(E, "solve(y == m x + b, x)", "[(y - b)/m]")
p(E, ["f(x) = x^2 - 2", "solve(f(x) == 0, x)"], "[-sqrt(2), sqrt(2)]")
p(E, "solve(1/x + 1/(x + 1) == 1, x)", "[1/2 - sqrt(5)/2, 1/2 + sqrt(5)/2]")
p(E, "solve(x^2 - 2 x + 1 == 0, x)", "[1]")

# ---------------------------------------------------------------- polynomials
P = "polynomials"
p(P, "degree(x^3 + x, x)", "3")
p(P, "coeff(3 x^2 + 2 x + 1, x, 2)", "3")
p(P, "coeffs(3 x^2 + 2 x + 1, x)", "[3, 2, 1]")
p(P, "discriminant(a x^2 + b x + c, x)", "b^2 - 4 a c")
p(P, "resultant(x^2 - 1, x - 1, x)", "0")
p(P, "quo(x^3 - 1, x - 1, x)", "x^2 + x + 1")
p(P, "rem(x^3, x - 2, x)", "8")
p(P, "interpolate([[1, 1], [2, 4], [3, 9]], x)", "x^2")
p(P, "horner(x^3 + 2 x^2 + 3 x + 4, x)", "x (x (x + 2) + 3) + 4")
p(P, "groebner([x^2 + y^2 - 1, x - y], x, y)", {"ok": True})
p(P, "factor(x^2 + 2 x y + y^2)", "(x + y)^2")
p(P, "expand((x - 1) (x + 1) (x^2 + 1))", "x^4 - 1")

# ---------------------------------------------------------------- calculus: derivatives
D = "derivatives"
p(D, "diff(x^3, x)", "3 x^2")
p(D, "diff(sin(x) x^2, x)", "x^2 cos(x) + 2 x sin(x)")
p(D, "diff(x^3, x, 2)", "6 x")
p(D, "diff(x^2 y^3, x, y)", "6 x y^2")
p(D, "diff(exp(x^2), x)", "2 x exp(x^2)")
p(D, "diff(ln(x), x)", "1/x")
p(D, "diff(tan(x), x)", "1 + tan(x)^2")
p(D, "diff(x^x, x)", "x^x (ln(x) + 1)")
p(D, "diff(asin(x), x)", "1/sqrt(1 - x^2)")
p(D, "diff(sqrt(1 + x^2), x)", "x/sqrt(1 + x^2)")
p(D, ["f(x) = x^3", "f'(2)"], "12")
p(D, ["f(x) = x^3", "f''(x)"], "6 x")
p(D, ["f(x) = sin(x)", "f'(x)"], "cos(x)")
p(D, ["g(t) = t^2 e^t", "g'(t)"], "t^2 e^t + 2 t e^t")
p(D, "doit(derivative(x^4, x))", "4 x^3")
p(D, "diff(abs(x), x)", {"ok": True})
p(D, "gradient(x^2 + y^2, [x, y])", "matrix([2 x, 2 y])")
p(D, "divergence([x^2, y^2], [x, y])", "2 x + 2 y")
p(D, "curl([-y, x, 0], [x, y, z])", "matrix([0, 0, 2])")
p(D, "laplacian(x^2 + y^2, [x, y])", "4")
p(D, "hessian(x^2 y, [x, y])", "matrix([[2 y, 2 x], [2 x, 0]])")
p(D, "jacobian([x y, x + y], [x, y])", "matrix([[y, x], [1, 1]])")

# ---------------------------------------------------------------- calculus: integrals
I = "integrals"
p(I, "integrate(x^2, x)", "x^3/3")
p(I, "integrate(x^2, x, 0, 1)", "1/3")
p(I, "integrate(1/x, x, 1, e)", "1")
p(I, "integrate(exp(-x^2), x, -oo, oo)", "sqrt(pi)")
p(I, "integrate(1/(1 + x^2), x, -oo, oo)", "pi")
p(I, "integrate(sin(x)^2, x)", "x/2 - sin(2 x)/4")
p(I, "integrate(x exp(x), x)", "(x - 1) exp(x)")
p(I, "integrate(ln(x), x)", "x ln(x) - x")
p(I, "integrate(sqrt(1 - x^2), x, -1, 1)", "pi/2")
p(I, "integrate(1/(x^2 - 1), x)", "ln(x - 1)/2 - ln(x + 1)/2")
p(I, "integrate(x y, x, 0, 1, y, 0, 2)", "1")
p(I, "integrate(x y, x, y)", "x^2 y^2/4")
p(I, "integrate(exp(-x) sin(x), x, 0, oo)", "1/2")
p(I, "integrate(x^2 exp(-x), x, 0, oo)", "2")
p(I, "integrate(1/sqrt(x), x, 0, 1)", "2")
p(I, "integrate(sec(x)^2, x)", "tan(x)")
p(I, "integrate(1/(x ln(x)), x)", "ln(ln(x))")
p(I, "integrate(cos(x)^3, x)", "sin(x) - sin(x)^3/3")
p(I, "integrate(x/(x^2 + 1), x)", "ln(x^2 + 1)/2")
p(I, "integrate(sin(x)/x, x, 0, oo)", "pi/2")
p(I, "integrate(heaviside(x - 1), x, 0, 2)", "1")
p(I, "integrate(dirac(x), x, -1, 1)", "1")
p(I, "doit(integral(x^2, x, 0, 1))", "1/3")
p(I, "integral(x^2, x, 0, 1)", {"contains": "Integral"})
p(I, "nintegrate(exp(-x^2), x, 0, 2)", {"contains": "0.88208139"})
p(I, "nintegrate(sin(x)/x, x, 0, 10)", {"contains": "1.6583475"})
p(I, "integrate(2 m x, x, 0, 3 s)", "9 m s^2")

# ---------------------------------------------------------------- limits & series
L = "limits and series"
p(L, "limit(sin(x)/x, x, 0)", "1")
p(L, "limit((1 + 1/n)^n, n, oo)", "e")
p(L, "limit(1/x, x, 0, 1)", "oo")
p(L, "limit(1/x, x, 0, -1)", "-oo")
p(L, "limit((x^2 - 1)/(x - 1), x, 1)", "2")
p(L, "limit(x ln(x), x, 0, 1)", "0")
p(L, "limit((1 - cos(x))/x^2, x, 0)", "1/2")
p(L, "limit(exp(-x) x^3, x, oo)", "0")
p(L, "limit((sqrt(x + 1) - 1)/x, x, 0)", "1/2")
p(L, "series(exp(x), x, 0, 4)", "1 + x + x^2/2 + x^3/6")
p(L, "series(sin(x), x, 0, 6)", "x - x^3/6 + x^5/120")
p(L, "series(ln(x), x, 1, 3)", "(x - 1) - (x - 1)^2/2")
p(L, "series(1/(1 - x), x, 0, 4)", "1 + x + x^2 + x^3")
p(L, "series(cos(x), x, 0, 6)", "1 - x^2/2 + x^4/24")
p(L, "series(atan(x), x, 0, 6)", "x - x^3/3 + x^5/5")
p(L, "sum(k, k, 1, n)", "n (n + 1)/2")
p(L, "sum(k^2, k, 1, n)", "n (n + 1) (2 n + 1)/6")
p(L, "sum(1/k^2, k, 1, oo)", "pi^2/6")
p(L, "sum(1/2^k, k, 0, oo)", "2")
p(L, "sum(binomial(n, k), k, 0, n)", "2^n")
p(L, "sum(1/(k (k + 1)), k, 1, oo)", "1")
p(L, "sum(x^k/k!, k, 0, oo)", "exp(x)")
p(L, "product(k, k, 1, n)", "n!")
p(L, "product(2, k, 1, n)", "2^n")
p(L, "fourier_series(x, x, 3)", "2 sin(x) - sin(2 x) + 2 sin(3 x)/3")

# ---------------------------------------------------------------- ODEs & recurrences
O = "differential equations"
p(O, "dsolve(D(y, x) == y, y, x)", {"contains": "C1*exp(x)"})
p(O, "dsolve(D(y, x, 2) + 4 y == 0, y, x)", {"contains": "sin(2*x)"})
p(O, "dsolve(D(y, x) == -2 y, y, x, 0, 3)", "3 exp(-2 x)")
p(O, "dsolve(D(y, x, 2) - y == x, y, x)", {"contains": "exp(x)"})
p(O, "dsolve(D(y, x) == x y, y, x, 0, 1)", "exp(x^2/2)")
p(O, "dsolve(D(y, x, 2) + y == 0, y, x, 0, 0, 1)", "sin(x)")
p(O, "dsolve(D(y, t) + 2 y == exp(-t), y, t, 0, 0)", "exp(-t) - exp(-2 t)")
p(O, "dsolve(D(y, x) == y^2, y, x, 0, 1)", "-1/(x - 1)")
p(O, ["sol = odesolve(-y, y, x, 0, 1, 5)", "sol(1)"], {"contains": "0.3678"})
p(O, ["sol = odesolve(-y, y, x, 0, 1, 5)", "sol(x)"], {"contains": "y_sol(x)"})
p("transforms", "laplace(f, t, s)", "f/s")
p(A, "solve(a x^2 + b x + c == 0, c)", "[-a x^2 - b x]")
p(S, ["assume x > 0, y != 0", "sqrt(x^2) y/y"], "x")
p(A, "s + t + m + g", "g + m + s + t")
p(O, "rsolve(a[n+1] == 2 a[n], a, n, 1)", "2^n")
p(O, "rsolve(a[n+2] == a[n+1] + a[n], a, n, 0, 1)", {"contains": "sqrt(5)"})
p(O, "rsolve(a[n+1] == a[n] + n, a, n, 0)", "n (n - 1)/2")

# ---------------------------------------------------------------- transforms
X = "transforms"
p(X, ["assume a > 0", "laplace(exp(-a t), t, s)"], "1/(s + a)")
p(X, "laplace(t^2, t, s)", "2/s^3")
p(X, "laplace(sin(t), t, s)", "1/(s^2 + 1)")
p(X, "laplace(heaviside(t - 1), t, s)", "exp(-s)/s")
p(X, "ilaplace(1/(s + a), s, t)", "exp(-a t) heaviside(t)")
p(X, "ilaplace(1/s^2, s, t)", "t heaviside(t)")
p(X, "ilaplace(s/(s^2 + 4), s, t)", "cos(2 t) heaviside(t)")
p(X, "fourier(exp(-x^2), x, k)", "sqrt(pi) exp(-pi^2 k^2)")
p(X, "ifourier(sqrt(pi) exp(-pi^2 k^2), k, x)", "exp(-x^2)")
p(X, "ztransform(1, n, z)", {"ok": True})

# ---------------------------------------------------------------- linear algebra
M = "linear algebra"
p(M, "det(matrix([[1, 2], [3, 4]]))", "-2")
p(M, "inv(matrix([[1, 2], [3, 4]]))", "matrix([[-2, 1], [3/2, -1/2]])")
p(M, "transpose(matrix([[1, 2], [3, 4]]))", "matrix([[1, 3], [2, 4]])")
p(M, "matrix([[1, 2], [3, 4]]) matrix([[1], [1]])", "matrix([[3], [7]])")
p(M, "matrix([[1, 2], [3, 4]])^2", "matrix([[7, 10], [15, 22]])")
p(M, "eigenvals(matrix([[2, 0], [0, 3]]))", "[2, 3]")
p(M, "eigenvals(matrix([[2, 1], [1, 2]]))", "[1, 3]")
p(M, "rank(matrix([[1, 2], [2, 4]]))", "1")
p(M, "nullspace(matrix([[1, 2], [2, 4]]))", "[matrix([-2, 1])]")
p(M, "trace(matrix([[1, 2], [3, 4]]))", "5")
p(M, "charpoly(matrix([[2, 1], [1, 2]]), lam)", "lam^2 - 4 lam + 3")
p(M, "rref(matrix([[1, 2, 3], [4, 5, 6]]))", "matrix([[1, 0, -1], [0, 1, 2]])")
p(M, "solve_linear(matrix([[2, 1], [1, 3]]), [3, 5])", "matrix([4/5, 7/5])")
p(M, "expm(matrix([[0, 1], [-1, 0]]) t)", "matrix([[cos(t), sin(t)], [-sin(t), cos(t)]])")
p(M, "dot([1, 2, 3], [4, 5, 6])", "32")
p(M, "cross([1, 0, 0], [0, 1, 0])", "matrix([0, 0, 1])")
p(M, "norm([3, 4])", "5")
p(M, "det(matrix([[a, b], [c, d]]))", "a d - b c")
p(M, "inv(matrix([[a, b], [c, d]]))", "matrix([[d, -b], [-c, a]])/(a d - b c)")
p(M, "det(identity(3))", "1")
p(M, "diagonalize(matrix([[2, 0], [0, 3]]))", {"ok": True})
p(M, "eigenvects(matrix([[2, 0], [0, 3]]))", {"ok": True})
p(M, "lu(matrix([[4, 3], [6, 3]]))", {"ok": True})
p(M, "qr(matrix([[1, 0], [0, 1]]))", {"ok": True})
p(M, "det(matrix([[1, 2, 3], [4, 5, 6], [7, 8, 10]]))", "-3")

# ---------------------------------------------------------------- number theory & combinatorics
N = "number theory"
p(N, "isprime(97)", {"contains": "True"})
p(N, "isprime(91)", {"contains": "False"})
p(N, "prime(10)", "29")
p(N, "nextprime(100)", "101")
p(N, "primefactors(360)", "[2, 3, 5]")
p(N, "factorint(360)", "[[2, 3], [3, 2], [5, 1]]")
p(N, "divisors(12)", "[1, 2, 3, 4, 6, 12]")
p(N, "totient(36)", "12")
p(N, "invmod(3, 7)", "5")
p(N, "powmod(2, 100, 7)", "2")
p(N, "mod(17, 5)", "2")
p(N, "fibonacci(10)", "55")
p(N, "bernoulli(4)", "-1/30")
p(N, "catalan(5)", "42")
p(N, "bell(4)", "15")
p(N, "stirling(4, 2)", "7")
p(N, "partitions(5)", "7")
p(N, "factorial2(7)", "105")
p(N, "rising(x, 3)", "x (x + 1) (x + 2)")
p(N, "multinomial(2, 1, 1)", "12")
p(N, "isqrt(50)", "7")

# ---------------------------------------------------------------- special functions
F = "special functions"
p(F, "gamma(1/2)", "sqrt(pi)")
p(F, "gamma(5)", "24")
p(F, "beta(2, 3)", "1/12")
p(F, "erf(oo)", "1")
p(F, "zeta(2)", "pi^2/6")
p(F, "zeta(4)", "pi^4/90")
p(F, "besselj(0, 0)", "1")
p(F, "legendre(2, x)", "(3 x^2 - 1)/2")
p(F, "hermite(2, x)", "4 x^2 - 2")
p(F, "chebyshevt(3, x)", "4 x^3 - 3 x")
p(F, "laguerre(2, x)", "x^2/2 - 2 x + 1")
p(F, "diff(erf(x), x)", "2 exp(-x^2)/sqrt(pi)")
p(F, "lambertw(0)", "0")
p(F, "digamma(1)", "-EulerGamma")
p(F, "integrate(exp(-x^2), x)", "sqrt(pi) erf(x)/2")
p(F, "elliptic_k(0)", "pi/2")

# ---------------------------------------------------------------- units (already tested; kept for coverage)
U = "units"
p(U, ["m = 2 kg", "a = 3 m/s^2", "F = m a -> N"], "6 N")
p(U, "5 km -> m", "5000 m")
p(U, "100 kmh -> m/s", "250 m/s / 9")
p(U, "2/s^3 + 1/s", "2/s^3 + 1/s")
p(U, "x = 3 m\nx -> cm", "300 cm")
p(U, "asin(1/2) -> deg", "30 deg")
p(U, "2 km + 3 m", "2003 m")
p(U, "1 kWh -> J", "3600000 J")

# ======================================================================
# Extended corpus
# ======================================================================

# ---------------------------------------------------------------- integrals: a table
I = "integrals"
p(I, ["assume a > 0", "integrate(1/(x^2 + a^2), x)"], "atan(x/a)/a")
p(I, ["assume a > 0", "integrate(exp(-a x^2), x, -oo, oo)"], "sqrt(pi/a)")
p(I, ["assume a > 0", "integrate(1/(x^2 + a^2), x, -oo, oo)"], "pi/a")
p(I, "integrate(x^2 exp(-x^2), x, -oo, oo)", "sqrt(pi)/2")
p(I, "integrate(1/(1 + x^4), x, 0, oo)", "sqrt(2) pi/4")
p(I, "integrate(ln(x)/(1 + x^2), x, 0, oo)", "0")
p(I, "integrate(x/(exp(x) - 1), x, 0, oo)", "pi^2/6")
p(I, "integrate(x^3/(exp(x) - 1), x, 0, oo)", "pi^4/15")
p(I, "integrate(sin(x)^2 cos(x)^2, x, 0, pi)", "pi/8")
p(I, "integrate(1/sqrt(1 - x^2), x)", "asin(x)")
p(I, "integrate(1/(x^2 + 2 x + 2), x)", "atan(x + 1)")
p(I, "integrate(x sin(x), x)", "sin(x) - x cos(x)")
p(I, "integrate(1/(x (x^2 + 1)), x)", "ln(x) - ln(x^2 + 1)/2")
p(I, "integrate(tan(x), x)", "-ln(cos(x))")
p(I, ["assume a > 0, b > 0", "simplify(diff(integrate(exp(a x) sin(b x), x), x) - exp(a x) sin(b x))"], "0")
p(I, "simplify(diff(integrate(sqrt(x^2 + 1), x), x) - sqrt(x^2 + 1))", "0")
p(I, "simplify(diff(integrate(1/cos(x), x), x) - 1/cos(x))", "0")
p(I, "simplify(diff(integrate(x^2 ln(x), x), x) - x^2 ln(x))", "0")
p(I, "simplify(diff(integrate(asin(x), x), x) - asin(x))", "0")
p(I, ["assume n positive integer", "integrate(exp(-x) x^n, x, 0, oo)"], "n!")
p(I, "integrate(x^2 sqrt(1 - x^2), x, -1, 1)", "pi/8")
p(I, "integrate(exp(-x) cos(x), x, 0, oo)", "1/2")
p(I, "integrate(sin(x)^3, x, 0, pi)", "4/3")
p(I, "integrate(1/(1 + exp(x)), x, 0, oo)", "ln(2)")
p(I, "integrate(ln(x)^2, x, 0, 1)", "2")
p(I, "integrate(x ln(x), x, 0, 1)", "-1/4")
p(I, "integrate(1/(1 + x^2)^2, x, -oo, oo)", "pi/2")
p(I, "integrate(x exp(-x^2), x)", "-exp(-x^2)/2")
p(I, "integrate(cos(x)^2, x, 0, 2 pi)", "pi")
p(I, "integrate(abs(x), x, -1, 1)", "1")
p(I, "integrate(piecewise((x, x < 1), (2 - x, x >= 1)), x, 0, 2)", "1")
p(I, "integrate(dirac(x - 1) x^2, x, 0, 2)", "1")
p(I, "integrate(exp(-x) heaviside(x), x, -oo, oo)", "1")
p(I, "integrate(1/(x^3 + 1), x, 0, oo)", "2 sqrt(3) pi/9")
p(I, "integrate(ln(1 + x)/x, x, 0, 1)", "pi^2/12")
p(I, "integrate(exp(-x^2) cos(x), x, -oo, oo)", "sqrt(pi) exp(-1/4)")
p(I, "integrate(erf(x), x)", "x erf(x) + exp(-x^2)/sqrt(pi)")
p(I, "integrate(x^2 + y^2, x, 0, 1, y, 0, 1)", "2/3")
p(I, "integrate(1, x, 0, 1, y, 0, 1, z, 0, 1)", "1")
p(I, "integrate(r, r, 0, R, theta, 0, 2 pi)", "pi R^2")
p(I, "integrate(exp(-x) sqrt(x), x, 0, oo)", "sqrt(pi)/2")
p(I, "integrate(sqrt(tan(x)), x, 0, pi/2)", "sqrt(2) pi/2")
p(I, "integrate(floor(x), x, 0, 3)", "3")
p(I, "integrate(1/(x^2 - 1), x, 2, 3)", "ln(3/2)/2")
p(I, "integrate(sin(x) exp(-x), x, 0, oo)", "1/2")
p(I, "integrate(x/sqrt(x^2 + 1), x)", "sqrt(x^2 + 1)")
p(I, "integrate(sin(x)^2, x, 0, pi)", "pi/2")
p(I, "integrate(cosh(x), x)", "sinh(x)")
p(I, "integrate(1/(e^x + e^(-x)), x, -oo, oo)", "pi/2")
p(I, "integrate(x^3 exp(-x), x, 0, oo)", "6")
p(I, "integrate(besselj(0, x), x, 0, oo)", "1")
p(I, ["assume m, n positive integer", "integrate(sin(m x) sin(n x), x, -pi, pi)"], {"ok": True})

# ---------------------------------------------------------------- derivatives (more)
D = "derivatives"
p(D, "diff(atan(x), x)", "1/(1 + x^2)")
p(D, "diff(acos(x), x)", "-1/sqrt(1 - x^2)")
p(D, "diff(sinh(x), x)", "cosh(x)")
p(D, "diff(x^(1/x), x)", "x^(1/x) (1 - ln(x))/x^2")
p(D, ["assume x real", "diff(abs(x), x)"], "sign(x)")
p(D, ["g(x) = sin(x^2)", "g'(x)"], "2 x cos(x^2)")
p(D, "diff(exp(2 x), x, 5)", "32 exp(2 x)")
p(D, "diff(x^n, x)", "n x^(n - 1)")
p(D, "diff(x^2 y + y^3, y)", "x^2 + 3 y^2")
p(D, "diff(exp(x y), x, y)", "(x y + 1) exp(x y)")
p(D, "solve(diff(x^3 - 3 x, x) == 0, x)", "[-1, 1]")
p(D, ["f(x) = x^2", "f(1) + f'(1) (x - 1)"], "2 x - 1")
p(D, "implicit_diff(x^2 + y^2 == 1, y, x)", "-x/y")
p(D, "implicit_diff(x^3 + y^3 == 6 x y, y, x)", "(2 y - x^2)/(y^2 - 2 x)")
p(D, "diff(ln(sin(x)), x)", "cos(x)/sin(x)")
p(D, "diff(sqrt(x), x, 2)", "-1/(4 x^(3/2))")
p(D, "diff(1/x, x, 3)", "-6/x^4")
p(D, ["f(x) = x^3", "g(x) = f(x) + 1", "g'(2)"], "12")
p(D, ["h(x, y) = x^2 y", "diff(h(x, y), x)"], "2 x y")
p(D, "diff(gamma(x), x)", "gamma(x) digamma(x)")
p(D, "diff(erf(x^2), x)", "4 x exp(-x^4)/sqrt(pi)")
p(D, "diff(lambertw(x), x)", "lambertw(x)/(x (lambertw(x) + 1))")
p(D, "subs(diff(x^3, x), x, 2)", "12")
p(D, "diff(x^2, x) + diff(y^2, y)", "2 x + 2 y")
p(D, "doit(derivative(sin(x) cos(x), x))", "cos(2 x)")

# ---------------------------------------------------------------- limits & series (more)
L = "limits and series"
p(L, "limit((1 + x)^(1/x), x, 0)", "e")
p(L, "limit(x^x, x, 0, 1)", "1")
p(L, "limit((exp(x) - 1 - x)/x^2, x, 0)", "1/2")
p(L, "limit(sqrt(x^2 + x) - x, x, oo)", "1/2")
p(L, "limit((1 + a/n)^n, n, oo)", "exp(a)")
p(L, "limit(n sin(1/n), n, oo)", "1")
p(L, "limit(x/(x + 1), x, oo)", "1")
p(L, "limit(tan(x)/x, x, 0)", "1")
p(L, "limit(cos(x)^(1/x^2), x, 0)", "exp(-1/2)")
p(L, "limit(ln(x)/x, x, oo)", "0")
p(L, "limit(atan(x), x, -oo)", "-pi/2")
p(L, "limit(abs(x)/x, x, 0, 1)", "1")
p(L, "limit(abs(x)/x, x, 0, -1)", "-1")
p(L, "limit(sum(1/k, k, 1, n) - ln(n), n, oo)", "EulerGamma")
p(L, "limit(n^(1/n), n, oo)", "1")
p(L, "limit((x^3 - 8)/(x - 2), x, 2)", "12")
p(L, "limit(sin(3 x)/sin(5 x), x, 0)", "3/5")
p(L, "limit(x exp(-x), x, oo)", "0")
p(L, "limit((2^x - 1)/x, x, 0)", "ln(2)")
p(L, "limit(1/(1 + exp(-1/x)), x, 0, 1)", "1")
p(L, "limit(1/(1 + exp(-1/x)), x, 0, -1)", "0")
p(L, "series(exp(x) sin(x), x, 0, 4)", "x + x^2 + x^3/3")
p(L, "series(tan(x), x, 0, 6)", "x + x^3/3 + 2 x^5/15")
p(L, "series(ln(1 + x), x, 0, 5)", "x - x^2/2 + x^3/3 - x^4/4")
p(L, "series(sqrt(1 + x), x, 0, 3)", "1 + x/2 - x^2/8")
p(L, "series((1 + x)^a, x, 0, 3)", "1 + a x + a (a - 1) x^2/2")
p(L, "series(1/x, x, 1, 3)", "x^2 - 3 x + 3")
p(L, "series(sinh(x), x, 0, 6)", "x + x^3/6 + x^5/120")
p(L, "series(asin(x), x, 0, 6)", "x + x^3/6 + 3 x^5/40")
p(L, "series(1/(x (1 - x)), x, 0, 3)", "1/x + 1 + x + x^2")
p(L, "series(exp(-x^2), x, 0, 5)", "1 - x^2 + x^4/2")
p(L, "series(x/(exp(x) - 1), x, 0, 4)", "1 - x/2 + x^2/12")
p(L, "fourier_series(x^2, x, 3)", "pi^2/3 - 4 cos(x) + cos(2 x)")
p(L, "sum(1/k^4, k, 1, oo)", "pi^4/90")
p(L, "sum((-1)^(k + 1)/k, k, 1, oo)", "ln(2)")
p(L, "sum(1/k!, k, 0, oo)", "e")
p(L, "sum(k/2^k, k, 1, oo)", "2")
p(L, "sum(k^3, k, 1, n)", "n^2 (n + 1)^2/4")
p(L, "sum(2 k - 1, k, 1, n)", "n^2")
p(L, "sum(1/2^k, k, 1, n)", "1 - 2^(-n)")
p(L, "sum(a r^k, k, 0, n - 1)", {"contains": "r**n"})
p(L, "sum(k, k, 1, 100)", "5050")
p(L, "sum(binomial(n, k) x^k, k, 0, n)", "(x + 1)^n")
p(L, "product(k/(k + 1), k, 1, n)", "1/(n + 1)")
p(L, "product(1 + 1/k, k, 1, n)", "n + 1")
p(L, "product(1 - 1/k^2, k, 2, n)", "(n + 1)/(2 n)")
p(L, "sum(sum(p q, q, 1, n), p, 1, n)", "n^2 (n + 1)^2/4")
p(L, "sum(1/(k^2 + k), k, 1, n)", "n/(n + 1)")
p(L, "sum(cos(k pi), k, 1, 4)", "0")
p(L, "sum(1/(4 k^2 - 1), k, 1, oo)", "1/2")
p(L, "sum((-1)^k/(2 k + 1), k, 0, oo)", "pi/4")
p(L, "sum(1/k^2, k, 1, 10)", "1968329/1270080")
p(L, "sum(x^k, k, 0, 3)", "x^3 + x^2 + x + 1")

# ---------------------------------------------------------------- equations (more)
E = "equations"
p(E, "solve(x^3 - x == 0, x)", "[-1, 0, 1]")
p(E, "solve(x^5 - x == 0, x)", "[-1, 0, 1, -i, i]")
p(E, "solve(exp(2 x) - 3 exp(x) + 2 == 0, x)", "[0, ln(2)]")
p(E, ["assume x > 0", "solve(ln(x) + ln(x - 1) == 0, x)"], "[1/2 + sqrt(5)/2]")
p(E, "solve(cos(x) == 1/2, x)", "[pi/3, 5 pi/3]")
p(E, "solve(tan(x) == 1, x)", "[pi/4]")
p(E, "solve([x^2 + y^2 == 1, y == x], [x, y])", "[[x == -sqrt(2)/2, y == -sqrt(2)/2], [x == sqrt(2)/2, y == sqrt(2)/2]]")
p(E, "solve(sqrt(x) + sqrt(x + 5) == 5, x)", "[4]")
p(E, "solve(2^x == 3^(x - 1), x)", "[ln(3)/(ln(3) - ln(2))]")
p(E, "solve(a x + b == c x + d, x)", "[(d - b)/(a - c)]")
p(E, "solve(x/(x - 1) == 2, x)", "[2]")
p(E, "solve(cosh(x) == 1, x)", "[0]")
p(E, "solve(x^2 == 2 x, x)", "[0, 2]")
p(E, "solve_real(x^3 == 8, x)", "[2]")
p(E, "solve_real(sin(x) == 0, x)", {"contains": "pi"})
p(E, "solve_real(exp(x) == -1, x)", "[]")
p(E, "solve_ineq(x^2 >= 1, x)", {"contains": "x <= -1"})
p(E, "solve_ineq((x - 1)/(x + 1) > 0, x)", {"contains": "1 < x"})
p(E, "solve_ineq([x > 0, x < 3], x)", {"contains": "(0 < x) & (x < 3)"})
p(E, "nsolve(x^3 - 2 x - 5 == 0, x, 2)", {"contains": "2.0945514"})
p(E, "nsolve(exp(-x) == x, x, 0.5)", {"contains": "0.567143"})
p(E, "solve([x + y == a, x - y == b], [x, y])", "[x == a/2 + b/2, y == a/2 - b/2]")
p(E, "solve_linear(matrix([[1, 1, 1], [0, 1, 1], [0, 0, 1]]), [6, 5, 3])", "matrix([1, 2, 3])")
p(E, "solve(x^2 - 2 a x + a^2 == 0, x)", "[a]")
p(E, "solve(z^2 == i, z)", "[-sqrt(2)/2 - sqrt(2) i/2, sqrt(2)/2 + sqrt(2) i/2]")
p(E, "solve(2 sin(x)^2 - 1 == 0, x)", {"contains": "pi/4"})
p(E, "solve(x^2 + 2 x + 5 == 0, x)", "[-1 - 2 i, -1 + 2 i]")
p(E, "solve(x^3 + 1 == 0, x)", "[-1, 1/2 - sqrt(3) i/2, 1/2 + sqrt(3) i/2]")
p(E, ["assume x real", "solve(e^x == e^(-x), x)"], "[0]")
p(E, "solve(10^x == 1000, x)", "[3]")
p(E, "solve(x^2 - x - 1 == 0, x)", "[1/2 - sqrt(5)/2, 1/2 + sqrt(5)/2]")
p(E, "solve(abs(2 x + 1) == 5, x)", "[-3, 2]")
p(E, "solve([x + 2 y + 3 z == 14, 2 x - y + z == 3, x + y + z == 6], [x, y, z])", "[x == 1, y == 2, z == 3]")
p(E, "solve([x y == 6, x + y == 5], [x, y])", "[[x == 2, y == 3], [x == 3, y == 2]]")
p(E, "solve([x^2 - y == 0, x - y == 0], [x, y])", "[[x == 0, y == 0], [x == 1, y == 1]]")
p(E, "solve(sin(x) == cos(x), x)", {"contains": "pi/4"})
p(E, "linsolve([x + y + z == 1, x - y == 0], x, y, z)", {"contains": "1/2 - z/2"})

# ---------------------------------------------------------------- assumptions (more)
S = "assumptions"
p(S, ["assume x real", "simplify(ln(exp(x)))"], "x")
p(S, ["assume n integer", "simplify(exp(2 pi i n))"], "1")
p(S, ["assume k integer", "simplify((-1)^(2 k + 1))"], "-1")
p(S, ["assume x > 0", "abs(x)"], "x")
p(S, ["assume x > 0", "sign(x)"], "1")
p(S, ["assume x < 0", "abs(x)"], "-x")
p(S, ["assume n positive integer", "gammasimp(factorial(n)/factorial(n - 1))"], "n")
p(S, ["assume a > 0, b > 0", "simplify(sqrt(a) sqrt(b))"], "sqrt(a b)")
p(S, ["assume x real", "re(x) + im(x) + conj(x)"], "2 x")
p(S, ["assume n odd", "simplify(cos(n pi))"], "-1")
p(S, ["assume x real", "simplify(abs(exp(i x)))"], "1")
p(S, ["assume x > 0", "(x^2)^(1/2)"], "x")
p(S, ["assume x > 0", "simplify(ln(x^2))"], "2 ln(x)")
p(S, ["assume x >= 0", "sqrt(x)^2"], "x")
p(S, ["assume t > 0", "assume n positive integer", "laplace(t^n, t, s)"], "n!/s^(n + 1)")
p(S, ["assume x real, y real", "simplify(abs(x + i y)^2)"], "x^2 + y^2")
p(S, ["assume n integer", "sum(cos(2 pi n k), k, 1, 3)"], "3")
p(S, ["assume x > 0", "solve(x^2 == 4, x)"], "[2]")
p(S, ["assume p prime", "isprime(7)"], {"contains": "True"})

# ---------------------------------------------------------------- trigonometry (more)
T = "trigonometry"
p(T, "simplify(sin(x)^4 - cos(x)^4 + cos(2 x))", "0")
p(T, "trigsimp(sin(x) cos(y) + cos(x) sin(y))", "sin(x + y)")
p(T, "expand_trig(sin(3 x))", "3 sin(x) - 4 sin(x)^3")
p(T, "simplify(tan(x) - sin(x)/cos(x))", "0")
p(T, "expand_trig(cos(x + y))", "cos(x) cos(y) - sin(x) sin(y)")
p(T, "rewrite(sin(x), exp)", "-i exp(i x)/2 + i exp(-i x)/2")
p(T, "sin(pi/12)", "sqrt(6)/4 - sqrt(2)/4")
p(T, "cos(pi/5)", "1/4 + sqrt(5)/4")
p(T, "acos(-1)", "pi")
p(T, "atan(oo)", "pi/2")
p(T, "sinh(ln(2))", "3/4")
p(T, "cos(60 deg)", "1/2")
p(T, "tan(45 deg)", "1")
p(T, "sin(x)^2 + cos(x)^2 - 1", {"ok": True})
p(T, "trigsimp(2 sin(x) cos(x))", "sin(2 x)")
p(T, "trigsimp(cos(x)^2 - sin(x)^2)", "cos(2 x)")
p(T, "simplify(sec(x)^2 - tan(x)^2)", "1")
p(T, "asin(sin(pi/6))", "pi/6")
p(T, "sin(x + 2 pi)", "sin(x)")
p(T, "cos(-x)", "cos(x)")
p(T, "sin(pi - x)", "sin(x)")
p(T, "atan(1) -> deg", "45 deg")
p(T, "acos(0) -> deg", "90 deg")

# ---------------------------------------------------------------- algebra (more)
A = "algebra"
p(A, "factor(x^3 + y^3)", "(x + y) (x^2 - x y + y^2)")
p(A, "factor(x^4 + 4)", "(x^2 - 2 x + 2) (x^2 + 2 x + 2)")
p(A, "factor(6 x^2 + 5 x - 6)", "(2 x + 3) (3 x - 2)")
p(A, "factor(x^2 - 2, sqrt(2))", "(x - sqrt(2)) (x + sqrt(2))")
p(A, "factor(x^2 + 1, i)", "(x - i) (x + i)")
p(A, "expand((x + y + z)^2)", "x^2 + y^2 + z^2 + 2 x y + 2 x z + 2 y z")
p(A, "expand((sqrt(2) + 1)^2)", "3 + 2 sqrt(2)")
p(A, "simplify((x^2 + 2 x + 1)/(x^2 - 1))", "(x + 1)/(x - 1)")
p(A, "apart(x^2/(x^2 - 1), x)", "1 + 1/(2 (x - 1)) - 1/(2 (x + 1))")
p(A, "apart(1/(x (x + 1)^2), x)", "1/x - 1/(x + 1) - 1/(x + 1)^2")
p(A, "cancel((x^3 - 1)/(x - 1))", "x^2 + x + 1")
p(A, "together(1/(x - 1) - 1/(x + 1))", "2/((x - 1) (x + 1))")
p(A, "simplify((sqrt(2) + sqrt(8))^2)", "18")
p(A, "radsimp(1/(sqrt(3) - sqrt(2)))", "sqrt(3) + sqrt(2)")
p(A, "nsimplify(0.125)", "1/8")
p(A, "coeff(expand((a + b)^5), a, 2)", "10 b^3")
p(A, "coeff(expand((1 + x)^10), x, 5)", "252")
p(A, "(2/3)^3", "8/27")
p(A, "mod(-7, 3)", "2")
p(A, "abs(-3)", "3")
p(A, "sign(-2)", "-1")
p(A, "floor(-2.5)", "-3")
p(A, "ceil(2.1)", "3")
p(A, "round(2.567, 2)", "2.57")
p(A, "(1 + i)^8", "16")
p(A, "polar(-1)", "[1, pi]")
p(A, "sqrt(i)", "sqrt(2)/2 + sqrt(2) i/2")
p(A, "i^i", "exp(-pi/2)")
p(A, "ln(-1)", "i pi")
p(A, "arg(-1 - i)", "-3 pi/4")
p(A, "re(1/(1 + i))", "1/2")
p(A, "simplify((x^3 - y^3)/(x - y))", "x^2 + x y + y^2")
p(A, "expand((x - 1)^2 (x + 1)^2)", "x^4 - 2 x^2 + 1")
p(A, "simplify(sqrt(x^4))", "sqrt(x^4)")
p(A, "powsimp(2^x 3^x)", "6^x")
p(A, "expand(exp(x + y))", "exp(x) exp(y)")
p(A, "logcombine(2 ln(x) - ln(y), force)", {"ok": True})
p(A, "simplify(e^(ln(2)))", "2")
p(A, "nsimplify(sqrt(2) + 0.5)", "sqrt(2) + 1/2")
p(A, "max(1, 2, 3)", "3")
p(A, "min([4, 2, 8])", "2")
p(A, "sign(-pi)", "-1")
p(A, "floor(7/2)", "3")
p(A, "gcd(x^3 - 1, x^2 - 1)", "x - 1")
p(A, "lcm(x^2 - 1, x - 1)", "x^2 - 1")
p(A, "subs(piecewise((x, x < 0), (x^2, x >= 0)), x, 2)", "4")
p(A, "diff(piecewise((x^2, x > 0), (0, x <= 0)), x)", {"ok": True})
p(A, "expand((a + b i) (a - b i))", "a^2 + b^2")
p(A, "simplify(1/(1/x + 1/y))", "x y/(x + y)")

# ---------------------------------------------------------------- polynomials (more)
P = "polynomials"
p(P, "roots(x^4 - 1, x)", "[-1, 1, -i, i]")
p(P, "degree(x^2 y^3, y)", "3")
p(P, "coeffs(x^3 - 1, x)", "[1, 0, 0, -1]")
p(P, "discriminant(x^3 + p x + q, x)", "-4 p^3 - 27 q^2")
p(P, "resultant(x^2 + 1, x^2 - 1, x)", "4")
p(P, "quo(x^4, x^2 + 1, x)", "x^2 - 1")
p(P, "rem(x^4, x^2 + 1, x)", "1")
p(P, "interpolate([[0, 1], [1, 2], [2, 5]], x)", "x^2 + 1")
p(P, "groebner([x^2 - y, y^2 - x], x, y)", {"ok": True})
p(P, "factor(x^6 - 1)", "(x - 1) (x + 1) (x^2 - x + 1) (x^2 + x + 1)")
p(P, "expand((x^2 + 1) (x^2 - 1))", "x^4 - 1")
p(P, "roots(x^2 - 2 x + 1, x)", "[1, 1]")
p(P, "solve(x^4 - 10 x^2 + 9 == 0, x)", "[-3, -1, 1, 3]")

# ---------------------------------------------------------------- linear algebra (more)
M = "linear algebra"
p(M, "det(matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))", "0")
p(M, "inv(matrix([[2, 0], [0, 4]]))", "matrix([[1/2, 0], [0, 1/4]])")
p(M, "eigenvals(matrix([[0, 1], [-1, 0]]))", "[-i, i]")
p(M, "eigenvals(matrix([[1, 2], [3, 4]]))", "[5/2 - sqrt(33)/2, 5/2 + sqrt(33)/2]")
p(M, "eigenvals(matrix([[2, 1], [0, 2]]))", "[2, 2]")
p(M, "nullspace(matrix([[1, 1, 1], [1, 1, 1]]))", "[matrix([-1, 1, 0]), matrix([-1, 0, 1])]")
p(M, "rank(identity(4))", "4")
p(M, "rank(zeros(2, 2))", "0")
p(M, "transpose(matrix([1, 2, 3]))", "matrix([[1, 2, 3]])")
p(M, "matrix([[1, 2], [3, 4]]) + identity(2)", "matrix([[2, 2], [3, 5]])")
p(M, "2 matrix([[1, 2], [3, 4]])", "matrix([[2, 4], [6, 8]])")
p(M, "det(matrix([[cos(t), -sin(t)], [sin(t), cos(t)]]))", "1")
p(M, ["Rot = matrix([[cos(t), -sin(t)], [sin(t), cos(t)]])", "simplify(inv(Rot) - transpose(Rot))"], "zeros(2, 2)")
p(M, "charpoly(identity(3), lam)", "(lam - 1)^3")
p(M, "trace(matrix([[a, b], [c, d]]) matrix([[p, q], [r, s]]))", "a p + b r + c q + d s")
p(M, "solve_linear(matrix([[a, 0], [0, b]]), [1, 1])", "matrix([1/a, 1/b])")
p(M, "eigenvects(matrix([[2, 1], [1, 2]]))", {"ok": True})
p(M, "dot([1, 2], [3, 4])", "11")
p(M, "cross([1, 2, 3], [4, 5, 6])", "matrix([-3, 6, -3])")
p(M, "norm([1, 1, 1])", "sqrt(3)")
p(M, "matrix([[1, 2], [3, 4]])^-1", "matrix([[-2, 1], [3/2, -1/2]])")
p(M, "det(diag(1, 2, 3))", "6")
p(M, "expm(zeros(2, 2))", "identity(2)")
p(M, ["LU = lu(matrix([[4, 3], [6, 3]]))", "LU[0] LU[1]"], "matrix([[4, 3], [6, 3]])")
p(M, "rref(matrix([[2, 1], [1, 3]]))", "identity(2)")
p(M, "qr(matrix([[1, 1], [0, 1]]))", {"ok": True})
p(M, "det(matrix([[1, a, a^2], [1, b, b^2], [1, c, c^2]]))", "(b - a) (c - a) (c - b)")
p(M, "det(jacobian([r cos(theta), r sin(theta)], [r, theta]))", "r")
p(M, "eigenvals(matrix([[1, 1], [1, 1]]))", "[0, 2]")
p(M, "diagonalize(matrix([[1, 1], [1, 1]]))", {"ok": True})
p(M, "inv(matrix([[1, 2, 3], [0, 1, 4], [5, 6, 0]]))", "matrix([[-24, 18, 5], [20, -15, -4], [-5, 4, 1]])")
p(M, "rank(matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))", "2")
p(M, "nullspace(matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]]))", "[matrix([1, -2, 1])]")
p(M, "transpose(matrix([[1, 2], [3, 4]])) matrix([[1, 2], [3, 4]])", "matrix([[10, 14], [14, 20]])")
p(M, "matrix([[1, 2], [3, 4]]) - matrix([[1, 2], [3, 4]])", "zeros(2, 2)")
p(M, "norm(matrix([3, 4]))", "5")

# ---------------------------------------------------------------- vector calculus (more)
V = "derivatives"
p(V, "gradient(x y z, [x, y, z])", "matrix([y z, x z, x y])")
p(V, "divergence([x, y, z], [x, y, z])", "3")
p(V, "curl([y z, x z, x y], [x, y, z])", "matrix([0, 0, 0])")
p(V, "simplify(laplacian(1/sqrt(x^2 + y^2 + z^2), [x, y, z]))", "0")
p(V, "laplacian(x^2 - y^2, [x, y])", "0")
p(V, "hessian(x^3 + y^3, [x, y])", "matrix([[6 x, 0], [0, 6 y]])")
p(V, "divergence(gradient(x^2 y, [x, y]), [x, y])", "2 y")
p(V, "curl(gradient(x y z, [x, y, z]), [x, y, z])", "matrix([0, 0, 0])")

# ---------------------------------------------------------------- ODEs & recurrences (more)
O = "differential equations"
p(O, "dsolve(D(y, x) == 2 x, y, x)", {"contains": "x**2"})
p(O, "dsolve(D(y, x) + y == x, y, x, 0, 0)", "x - 1 + exp(-x)")
p(O, "dsolve(D(y, x, 2) - 3 D(y, x) + 2 y == 0, y, x, 0, 1, 0)", "2 exp(x) - exp(2 x)")
p(O, "dsolve(D(y, x, 2) + 2 D(y, x) + y == 0, y, x)", {"contains": "exp(-x)"})
p(O, ["assume omega > 0", "dsolve(D(y, x, 2) + omega^2 y == 0, y, x)"], {"contains": "cos(omega*x)"})
p(O, "dsolve(x D(y, x) == y, y, x)", {"contains": "C1*x"})
p(O, "dsolve(D(y, x) == y (1 - y), y, x, 0, 1/2)", "1/(1 + exp(-x))")
p(O, "dsolve(D(y, x) == -y/x, y, x, 1, 2)", "2/x")
p(O, "dsolve(D(y, x) - y == exp(x), y, x, 0, 0)", "x exp(x)")
p(O, "dsolve(D(y, x) + y == y^2, y, x)", {"contains": "exp"})
p(O, "dsolve(D(y, x) == x/y, y, x)", {"ok": True})
p(O, "dsolve(D(y, t, 2) + 4 D(y, t) + 4 y == 0, y, t, 0, 1, 0)", "(2 t + 1) exp(-2 t)")
p(O, "dsolve(D(y, t, 2) + y == sin(2 t), y, t, 0, 0, 0)", "2 sin(t)/3 - sin(2 t)/3")
p(O, "dsolve(D(y, x) == cos(x), y, x, 0, 0)", "sin(x)")
p(O, "dsolve(D(y, x) == exp(x) - y, y, x, 0, 0)", "sinh(x)")
p(O, ["sols = odesolve([v, -y], [y, v], x, 0, [1, 0], 10)", "round(sols[0](pi), 4)"], "-1")
p(O, "rsolve(a[n+1] == a[n] + 2, a, n, 1)", "2 n + 1")
p(O, "rsolve(a[n+2] == 2 a[n+1] - a[n], a, n, 0, 1)", "n")
p(O, "rsolve(a[n+1] == 3 a[n] + 1, a, n, 0)", "3^n/2 - 1/2")
p(O, "rsolve(a[n+1] == a[n]/2, a, n, 8)", "8/2^n")
p(O, ["fib = rsolve(a[n+2] == a[n+1] + a[n], a, n, 0, 1)", "simplify(subs(fib, n, 10))"], "55")

# ---------------------------------------------------------------- transforms (more)
X = "transforms"
p(X, "laplace(cos(t), t, s)", "s/(s^2 + 1)")
p(X, "laplace(t exp(2 t), t, s)", "1/(s - 2)^2")
p(X, "laplace(dirac(t), t, s)", "1")
p(X, "laplace(t exp(-t), t, s)", "1/(s + 1)^2")
p(X, "laplace(sinh(t), t, s)", "1/(s^2 - 1)")
p(X, "laplace(heaviside(t), t, s)", "1/s")
p(X, "laplace(exp(-t) cos(t), t, s)", "(s + 1)/((s + 1)^2 + 1)")
p(X, "ilaplace(1/(s^2 + 1), s, t)", "sin(t) heaviside(t)")
p(X, "ilaplace(1/((s + 1) (s + 2)), s, t)", "(exp(-t) - exp(-2 t)) heaviside(t)")
p(X, "ilaplace(1, s, t)", "dirac(t)")
p(X, ["assume a > 0", "ilaplace(s/(s^2 + a^2), s, t)"], "cos(a t) heaviside(t)")
p(X, "ilaplace(1/s^3, s, t)", "t^2 heaviside(t)/2")
p(X, "fourier(exp(-abs(x)), x, k)", "2/(4 pi^2 k^2 + 1)")
p(X, "fourier(dirac(x), x, k)", "1")
p(X, ["assume a > 0", "fourier(exp(-a x^2), x, k)"], "sqrt(pi/a) exp(-pi^2 k^2/a)")
p(X, "ztransform(a^n, n, z)", {"contains": "z"})
p(X, ["assume a > 0", "laplace(exp(-a t) sin(t), t, s)"], "1/((s + a)^2 + 1)")
p(X, "simplify(ilaplace(laplace(t^3, t, s), s, t))", "t^3 heaviside(t)")

# ---------------------------------------------------------------- number theory (more)
N = "number theory"
p(N, "factorint(2^10 3^5)", "[[2, 10], [3, 5]]")
p(N, "gcd(2^100 - 1, 2^60 - 1)", "2^20 - 1")
p(N, "powmod(3, 100, 7)", "4")
p(N, "isprime(2^31 - 1)", {"contains": "True"})
p(N, "nextprime(10^6)", "1000003")
p(N, "prevprime(100)", "97")
p(N, "prime(100)", "541")
p(N, "totient(97)", "96")
p(N, "primefactors(1001)", "[7, 11, 13]")
p(N, "invmod(17, 3120)", "2753")
p(N, "fibonacci(50)", "12586269025")
p(N, "binomial(50, 25)", "126410606437752")
p(N, "20!", "2432902008176640000")
p(N, "catalan(10)", "16796")
p(N, "bernoulli(10)", "5/66")
p(N, "euler_number(4)", "5")
p(N, "stirling(5, 3)", "25")
p(N, "partitions(100)", "190569292")
p(N, "legendre_symbol(3, 7)", "-1")
p(N, "isqrt(10^10)", "100000")
p(N, "mod(2^100, 101)", "1")
p(N, "binomial(n, 2)", "n (n - 1)/2")
p(N, "gammasimp(factorial(n)/factorial(n - 2))", "n (n - 1)")
p(N, "sum(binomial(5, k), k, 0, 5)", "32")
p(N, "rising(3, 2)", "12")
p(N, "falling(5, 2)", "20")
p(N, "multinomial(1, 1, 1)", "6")
p(N, "bell(5)", "52")
p(N, "stirling(5, 2)", "15")
p(N, "partitions(10)", "42")
p(N, "divisors(28)", "[1, 2, 4, 7, 14, 28]")
p(N, "lcm(lcm(12, 18), 30)", "180")

# ---------------------------------------------------------------- special functions (more)
F = "special functions"
p(F, "gamma(3/2)", "sqrt(pi)/2")
p(F, "gamma(-1/2)", "-2 sqrt(pi)")
p(F, "beta(1/2, 1/2)", "pi")
p(F, "erf(0)", "0")
p(F, "erf(-x)", "-erf(x)")
p(F, "erfinv(0)", "0")
p(F, "zeta(0)", "-1/2")
p(F, "zeta(-1)", "-1/12")
p(F, "polylog(2, 1)", "pi^2/6")
p(F, "lambertw(e)", "1")
p(F, "besselj(1/2, x)", "sqrt(2) sin(x)/(sqrt(pi) sqrt(x))")
p(F, "legendre(3, x)", "(5 x^3 - 3 x)/2")
p(F, "hermite(3, x)", "8 x^3 - 12 x")
p(F, "chebyshevu(2, x)", "4 x^2 - 1")
p(F, "laguerre(1, x)", "1 - x")
p(F, "jacobi(1, 0, 0, x)", "x")
p(F, "digamma(1/2)", "-EulerGamma - 2 ln(2)")
p(F, "Si(oo)", "pi/2")
p(F, "Ci(oo)", "0")
p(F, "elliptic_e(0)", "pi/2")
p(F, "airyai(0)", "3^(1/3)/(3 gamma(2/3))")
p(F, "heaviside(0)", "1/2")
p(F, "kronecker(1, 1)", "1")
p(F, "kronecker(1, 2)", "0")
p(F, "gamma(x + 1) - x gamma(x)", "0")
p(F, "series(gamma(x), x, 0, 2)", {"contains": "EulerGamma"})
p(F, "simplify(erf(x) + erfc(x))", "1")
p(F, "besselj(0, x) diff(bessely(0, x), x) - bessely(0, x) diff(besselj(0, x), x)", {"ok": True})

# ---------------------------------------------------------------- worksheet with units
U = "units"
p(U, ["x = 3 m", "y = 4 m", "sqrt(x^2 + y^2)"], "5 m")
p(U, ["v = 10 m/s", "t = 5 s", "v t -> km"], "1/20 km")
p(U, ["P = 100 W", "t = 2 hr", "P t -> kWh"], "1/5 kWh")
p(U, ["rho = 1000 kg/m^3", "V = 2 L", "rho V -> kg"], "2 kg")
p(U, ["f = 50 Hz", "1/f -> ms"], "20 ms")
p(U, ["I = 2 A", "R = 10 ohm", "I R -> V"], "20 V")
p(U, "1 eV -> J", {"contains": "1.60217"})
p(U, ["theta = 90 deg", "sin(theta)"], "1")
p(U, ["theta = pi/6", "theta -> deg"], "30 deg")
p(U, ["a = 9.81 m/s^2", "h = 10 m", "sqrt(2 a h)"], {"contains": "14.007"})
p(U, "1 m + 1 kg", {"error": "Cannot add"})
p(U, "1 m -> kg", {"error": "Cannot convert"})
p(U, ["f(x) = x^2", "f(3 m)"], "9 m^2")
p(U, ["T = 300 K", "k_B T -> eV"], {"contains": "0.02585"})
p(U, "c_light -> km/s", "149896229 km/s / 500")
p(U, "g_0 -> ft/s^2", {"contains": "32.17"})
p(U, ["E(m) = m c_light^2", "E(1 kg) -> J"], "89875517873681764 J")
p(U, ["omega = 2 pi 50 Hz", "omega -> rad/s"], "100 rad/s pi")
p(U, ["A = 2 m 3 m", "A -> cm^2"], "60000 cm^2")
p(U, ["V = 1 L -> m^3"], "1 m^3 / 1000")
p(U, "3 ft + 2 inch -> cm", "9652/100 cm")
p(U, ["p = 1 atm -> kPa"], "101325/1000 kPa")
p(U, ["m = 70 kg", "g = 9.81 m/s^2", "W = m g -> N"], {"contains": "686.7"})
p(U, "sqrt(4 m^2)", "2 m")
p(U, "(3 m)^2", "9 m^2")
p(U, ["d = 100 m", "t = 9.58 s", "d/t -> kmh"], {"contains": "37.578"})
p(U, "1 kg m/s^2 -> N", "1 N")
p(U, "1 N m -> J", "1 J")
p(U, "1 J/s -> W", "1 W")
p(U, "1 V/A -> ohm", "1 ohm")
p(U, "1 C/V -> F", "1 F")
p(U, "1 rpm -> Hz", "1/60 Hz")
p(U, ["x = 2 m", "x^3 -> L"], "8000 L")

# ---------------------------------------------------------------- stats module
ST = "stats"
p(ST, "mean([2, 4, 4, 4, 5, 5, 7, 9])", "5")
p(ST, "stdev([2, 4, 4, 4, 5, 5, 7, 9])", "sqrt(32/7)")
p(ST, "median([3, 1, 2])", "2")
p(ST, "median([1, 2, 3, 4])", "5/2")
p(ST, "variance([1, 2, 3, 4])", "5/3")
p(ST, "correlation([1, 2, 3], [2, 4, 6])", "1")
p(ST, "linfit([1, 2, 3], [2, 4, 6])", "[2, 0]")
p(ST, "mean([x, y])", "(x + y)/2")
p(ST, ["xs = [1, 2, 3]", "mean(xs) + stdev(xs)"], "3")
